### ISSUE TITLE
Issues with the example

### ISSUE THREAD

**Issue by murmelbahn** [custom-components/sensor.stadtreinigung_hamburg#1]
Hi,
at first I have to thank you for your awesome custom component. 
I can see when my trash is ready to go but I can't get the binary sensor to working.
Im using it like this:
```yaml
  - platform: template
    sensors:
      morgen_schwarze_tonne:
        friendly_name: "schwarze Tonne (morgen)"
        value_template: >-
          {% set collection = states.sensor.stadtreinigung_hamburg_home_schwarze_restmulltonne.state %}
          {% set tomorrow = (as_timestamp(now()) + 86400)|timestamp_custom("%Y-%m-%d") %}
          {{ collection == tomorrow }}
```

I've created a notification which should fire when the binary_sensor changed its state to on:

```yaml
  - alias: 'Benachrichtigung wenn Restmuell'
    trigger:
      platform: state
      entity_id: binary_sensor.morgen_schwarze_tonne
      to: 'on'
    action:
      - service: notify.ios_users
        data:
          title: "Morgen wird Müll abgeholt"
          message: "Restmüll wird abgeholt."
      - service: persistent_notification.create
        data:
          title: "Morgen wird Müll abgeholt"
          message: "Restmüll wird abgeholt."
          notification_id: muell_rest       
```

Can you give me a hint what might be wrong?
Thanks in advance.

**Comment by vigonotion** [comment]
Is the binary sensor itself working (is the state on one day before the collection)? Or is it just the automation that isn't working?

**Comment by murmelbahn** [comment]
Should the binary sensor have the on state the whole day before the collection? If yes then die binary sensor isn't working.

**Comment by vigonotion** [comment]
```yaml
  - platform: template
    sensors:
      morgen_schwarze_tonne:
        friendly_name: "schwarze Tonne (morgen)"
        value_template: >-
          {% set collection = as_timestamp(states.sensor.stadtreinigung_hamburg_home_schwarze_restmulltonne.state)|timestamp_custom("%Y-%m-%d") %}
          {% set tomorrow = (as_timestamp(now()) + 86400)|timestamp_custom("%Y-%m-%d") %}
          {{ collection == tomorrow }}
```

Please try that. Difference here is the set collection line, it had to be converted to a timestamp without the time, only the date.
Let me know if it works for you, then I'll update the example
